-- OM Value Homes CMS schema and security policies.
-- Safe to run again: existing content is preserved and missing CMS fields are added.
-- Create the approved Supabase Auth user before running this file.

create or replace function public.set_updated_at()
returns trigger
language plpgsql
security invoker
set search_path = ''
as $$
begin
  new.updated_at = timezone('utc', now());
  return new;
end;
$$;

create table if not exists public.content_admins (
  user_id uuid primary key references auth.users(id) on delete cascade,
  created_at timestamptz not null default timezone('utc', now())
);

alter table public.content_admins enable row level security;
revoke all on table public.content_admins from anon, authenticated;

insert into public.content_admins (user_id)
select id
from auth.users
where lower(email) = 'omvaluehomes6@gmail.com'
on conflict (user_id) do nothing;

create or replace function public.is_content_admin()
returns boolean
language sql
stable
security definer
set search_path = ''
as $$
  select exists (
    select 1
    from public.content_admins
    where user_id = (select auth.uid())
  );
$$;

revoke all on function public.is_content_admin() from public;
grant execute on function public.is_content_admin() to authenticated;

create table if not exists public.blog_posts (
  id bigint generated by default as identity primary key,
  slug text not null unique,
  title text not null,
  excerpt text not null,
  category text not null,
  body text not null,
  seo_title text not null,
  seo_description text not null,
  cover_path text,
  image_alt text not null default '',
  video_url text,
  published_at date not null default current_date,
  updated_at timestamptz not null default timezone('utc', now())
);

alter table public.blog_posts add column if not exists image_alt text not null default '';
alter table public.blog_posts add column if not exists video_url text;

create table if not exists public.founder_profiles (
  id bigint generated by default as identity primary key,
  name text not null,
  role text not null,
  headline text not null,
  bio text not null,
  image_path text,
  sort_order integer not null default 1 check (sort_order > 0),
  updated_at timestamptz not null default timezone('utc', now())
);

alter table public.founder_profiles
  drop constraint if exists founder_profiles_id_check;
alter table public.founder_profiles
  add column if not exists sort_order integer not null default 1;

do $$
declare
  founder_sequence text;
  founder_max_id bigint;
begin
  founder_sequence := pg_get_serial_sequence('public.founder_profiles', 'id');
  if founder_sequence is null then
    create sequence if not exists public.founder_profiles_id_seq;
    alter sequence public.founder_profiles_id_seq
      owned by public.founder_profiles.id;
    alter table public.founder_profiles
      alter column id set default nextval('public.founder_profiles_id_seq');
    founder_sequence := 'public.founder_profiles_id_seq';
  end if;

  select coalesce(max(id), 0) into founder_max_id
  from public.founder_profiles;
  if founder_max_id = 0 then
    perform setval(founder_sequence::regclass, 1, false);
  else
    perform setval(founder_sequence::regclass, founder_max_id, true);
  end if;
end;
$$;

create table if not exists public.founder_projects (
  id bigint generated by default as identity primary key,
  stage text not null check (stage in ('Previous', 'Latest', 'Upcoming')),
  title text not null,
  status text not null,
  description text not null,
  image_path text,
  sort_order integer not null default 1 check (sort_order > 0),
  updated_at timestamptz not null default timezone('utc', now())
);

create table if not exists public.customer_stories (
  id bigint generated by default as identity primary key,
  name text not null,
  title text not null,
  story text not null,
  orientation text not null check (orientation in ('portrait', 'landscape')),
  image_path text,
  sort_order integer not null default 1 check (sort_order > 0),
  updated_at timestamptz not null default timezone('utc', now())
);

create table if not exists public.flat_tours (
  id bigint generated by default as identity primary key,
  title text not null,
  bhk_label text not null unique,
  video_source text not null default 'storage'
    check (video_source in ('storage', 'youtube')),
  video_path text,
  video_url text,
  embed_html text,
  file_name text,
  content_type text,
  file_size bigint,
  updated_at timestamptz not null default timezone('utc', now()),
  check (
    (video_source = 'storage' and video_path is not null)
    or (video_source = 'youtube' and video_url is not null)
  )
);

create table if not exists public.property_types (
  id bigint generated by default as identity primary key,
  slug text not null unique,
  display_number text not null,
  bhk_label text not null unique,
  price text not null,
  area text not null,
  status text not null,
  headline text not null,
  overview text not null,
  ideal_for text not null,
  highlights text not null,
  meta_title text not null,
  meta_description text not null,
  image_path text,
  sort_order integer not null default 1 check (sort_order > 0),
  is_visible boolean not null default true,
  updated_at timestamptz not null default timezone('utc', now())
);

create table if not exists public.amenities (
  id bigint generated by default as identity primary key,
  title text not null,
  description text not null,
  sort_order integer not null default 1 check (sort_order > 0),
  is_visible boolean not null default true,
  updated_at timestamptz not null default timezone('utc', now())
);

create table if not exists public.faqs (
  id bigint generated by default as identity primary key,
  question text not null,
  answer text not null,
  sort_order integer not null default 1 check (sort_order > 0),
  is_visible boolean not null default true,
  updated_at timestamptz not null default timezone('utc', now())
);

create table if not exists public.site_settings (
  id bigint primary key default 1 check (id = 1),
  hero_eyebrow text not null,
  hero_title text not null,
  hero_lead text not null,
  price_label text not null,
  price_value text not null,
  project_kicker text not null,
  project_title text not null,
  project_description text not null,
  homes_title text not null,
  homes_description text not null,
  amenities_title text not null,
  amenities_description text not null,
  blogs_title text not null,
  blogs_description text not null,
  location_title text not null,
  location_description text not null,
  address text not null,
  map_embed_url text not null,
  google_maps_link text not null,
  whatsapp_number text not null,
  whatsapp_display text not null,
  call_number text not null,
  call_display text not null,
  rera_number text not null,
  updated_at timestamptz not null default timezone('utc', now())
);

do $$
declare
  table_name text;
begin
  foreach table_name in array array[
    'blog_posts',
    'founder_profiles',
    'founder_projects',
    'customer_stories',
    'flat_tours',
    'property_types',
    'amenities',
    'faqs',
    'site_settings'
  ]
  loop
    execute format('drop trigger if exists %I_set_updated_at on public.%I', table_name, table_name);
    execute format(
      'create trigger %I_set_updated_at before update on public.%I for each row execute function public.set_updated_at()',
      table_name,
      table_name
    );
    execute format('alter table public.%I enable row level security', table_name);
  end loop;
end;
$$;

grant usage on schema public to anon, authenticated;

do $$
declare
  table_name text;
begin
  foreach table_name in array array[
    'blog_posts',
    'founder_profiles',
    'founder_projects',
    'customer_stories',
    'flat_tours',
    'property_types',
    'amenities',
    'faqs',
    'site_settings'
  ]
  loop
    execute format('grant select on public.%I to anon, authenticated', table_name);
    execute format('grant insert, update, delete on public.%I to authenticated', table_name);
    execute format('drop policy if exists "Public reads %s" on public.%I', table_name, table_name);
    execute format(
      'create policy "Public reads %s" on public.%I for select to anon, authenticated using (true)',
      table_name,
      table_name
    );
    execute format('drop policy if exists "Admin manages %s" on public.%I', table_name, table_name);
    execute format(
      'create policy "Admin manages %s" on public.%I for all to authenticated using (public.is_content_admin()) with check (public.is_content_admin())',
      table_name,
      table_name
    );
  end loop;
end;
$$;

grant usage, select on all sequences in schema public to authenticated;

insert into storage.buckets
  (id, name, public, file_size_limit, allowed_mime_types)
values
  (
    'content-media',
    'content-media',
    true,
    10485760,
    array['image/jpeg', 'image/png', 'image/webp', 'image/gif']
  ),
  (
    'flat-tours',
    'flat-tours',
    true,
    524288000,
    array['video/mp4', 'video/webm', 'video/quicktime']
  )
on conflict (id) do update set
  public = excluded.public,
  file_size_limit = excluded.file_size_limit,
  allowed_mime_types = excluded.allowed_mime_types;

drop policy if exists "Public reads OM content media" on storage.objects;
create policy "Public reads OM content media"
on storage.objects for select
to anon, authenticated
using (bucket_id in ('content-media', 'flat-tours'));

drop policy if exists "Admin uploads OM content media" on storage.objects;
create policy "Admin uploads OM content media"
on storage.objects for insert
to authenticated
with check (
  bucket_id in ('content-media', 'flat-tours')
  and public.is_content_admin()
  and (
    (bucket_id = 'content-media' and name like 'content/%')
    or (bucket_id = 'flat-tours' and name like 'tours/%')
  )
);

drop policy if exists "Admin updates OM content media" on storage.objects;
create policy "Admin updates OM content media"
on storage.objects for update
to authenticated
using (
  bucket_id in ('content-media', 'flat-tours')
  and public.is_content_admin()
)
with check (
  bucket_id in ('content-media', 'flat-tours')
  and public.is_content_admin()
);

drop policy if exists "Admin deletes OM content media" on storage.objects;
create policy "Admin deletes OM content media"
on storage.objects for delete
to authenticated
using (
  bucket_id in ('content-media', 'flat-tours')
  and public.is_content_admin()
);

do $$
declare
  table_name text;
begin
  foreach table_name in array array[
    'blog_posts',
    'founder_profiles',
    'founder_projects',
    'customer_stories',
    'flat_tours',
    'property_types',
    'amenities',
    'faqs',
    'site_settings'
  ]
  loop
    if not exists (
      select 1
      from pg_publication_tables
      where pubname = 'supabase_realtime'
        and schemaname = 'public'
        and tablename = table_name
    ) then
      execute format(
        'alter publication supabase_realtime add table public.%I',
        table_name
      );
    end if;
  end loop;
end;
$$;
