-- OM Value Homes content database for the Supabase/Vercel deployment.
-- Run this once in the Supabase SQL Editor after creating the project.

create or replace function public.set_updated_at()
returns trigger
language plpgsql
security invoker
set search_path = ''
as $$
begin
  new.updated_at = timezone('utc', now());
  return new;
end;
$$;

create or replace function public.is_content_admin()
returns boolean
language sql
stable
security invoker
set search_path = ''
as $$
  select coalesce((select auth.jwt() ->> 'email'), '') = 'omvaluehomes6@gmail.com';
$$;

create table if not exists public.blog_posts (
  id bigint generated by default as identity primary key,
  slug text not null unique,
  title text not null,
  excerpt text not null,
  category text not null,
  body text not null,
  seo_title text not null,
  seo_description text not null,
  cover_path text,
  published_at date not null default current_date,
  updated_at timestamptz not null default timezone('utc', now())
);

create table if not exists public.founder_profiles (
  id bigint primary key default 1 check (id = 1),
  name text not null,
  role text not null,
  headline text not null,
  bio text not null,
  image_path text,
  updated_at timestamptz not null default timezone('utc', now())
);

create table if not exists public.founder_projects (
  id bigint generated by default as identity primary key,
  stage text not null check (stage in ('Previous', 'Latest', 'Upcoming')),
  title text not null,
  status text not null,
  description text not null,
  image_path text,
  sort_order integer not null default 1,
  updated_at timestamptz not null default timezone('utc', now())
);

create table if not exists public.customer_stories (
  id bigint generated by default as identity primary key,
  name text not null,
  title text not null,
  story text not null,
  orientation text not null check (orientation in ('portrait', 'landscape')),
  image_path text,
  sort_order integer not null default 1,
  updated_at timestamptz not null default timezone('utc', now())
);

create table if not exists public.flat_tours (
  id bigint generated by default as identity primary key,
  title text not null,
  bhk_label text not null unique,
  video_source text not null default 'storage' check (video_source in ('storage', 'youtube')),
  video_path text,
  video_url text,
  embed_html text,
  file_name text,
  content_type text,
  file_size bigint,
  updated_at timestamptz not null default timezone('utc', now())
);

drop trigger if exists blog_posts_set_updated_at on public.blog_posts;
create trigger blog_posts_set_updated_at
before update on public.blog_posts
for each row execute function public.set_updated_at();

drop trigger if exists founder_profiles_set_updated_at on public.founder_profiles;
create trigger founder_profiles_set_updated_at
before update on public.founder_profiles
for each row execute function public.set_updated_at();

drop trigger if exists founder_projects_set_updated_at on public.founder_projects;
create trigger founder_projects_set_updated_at
before update on public.founder_projects
for each row execute function public.set_updated_at();

drop trigger if exists customer_stories_set_updated_at on public.customer_stories;
create trigger customer_stories_set_updated_at
before update on public.customer_stories
for each row execute function public.set_updated_at();

drop trigger if exists flat_tours_set_updated_at on public.flat_tours;
create trigger flat_tours_set_updated_at
before update on public.flat_tours
for each row execute function public.set_updated_at();

alter table public.blog_posts enable row level security;
alter table public.founder_profiles enable row level security;
alter table public.founder_projects enable row level security;
alter table public.customer_stories enable row level security;
alter table public.flat_tours enable row level security;

grant usage on schema public to anon, authenticated;
grant select on public.blog_posts to anon, authenticated;
grant select on public.founder_profiles to anon, authenticated;
grant select on public.founder_projects to anon, authenticated;
grant select on public.customer_stories to anon, authenticated;
grant select on public.flat_tours to anon, authenticated;
grant insert, update, delete on public.blog_posts to authenticated;
grant insert, update, delete on public.founder_profiles to authenticated;
grant insert, update, delete on public.founder_projects to authenticated;
grant insert, update, delete on public.customer_stories to authenticated;
grant insert, update, delete on public.flat_tours to authenticated;
grant usage, select on all sequences in schema public to authenticated;
grant execute on function public.is_content_admin() to anon, authenticated;

drop policy if exists "Public can read blog posts" on public.blog_posts;
create policy "Public can read blog posts"
on public.blog_posts for select
to anon, authenticated
using (true);

drop policy if exists "Admin manages blog posts" on public.blog_posts;
create policy "Admin manages blog posts"
on public.blog_posts for all
to authenticated
using (public.is_content_admin())
with check (public.is_content_admin());

drop policy if exists "Public can read founder profiles" on public.founder_profiles;
create policy "Public can read founder profiles"
on public.founder_profiles for select
to anon, authenticated
using (true);

drop policy if exists "Admin manages founder profiles" on public.founder_profiles;
create policy "Admin manages founder profiles"
on public.founder_profiles for all
to authenticated
using (public.is_content_admin())
with check (public.is_content_admin());

drop policy if exists "Public can read founder projects" on public.founder_projects;
create policy "Public can read founder projects"
on public.founder_projects for select
to anon, authenticated
using (true);

drop policy if exists "Admin manages founder projects" on public.founder_projects;
create policy "Admin manages founder projects"
on public.founder_projects for all
to authenticated
using (public.is_content_admin())
with check (public.is_content_admin());

drop policy if exists "Public can read customer stories" on public.customer_stories;
create policy "Public can read customer stories"
on public.customer_stories for select
to anon, authenticated
using (true);

drop policy if exists "Admin manages customer stories" on public.customer_stories;
create policy "Admin manages customer stories"
on public.customer_stories for all
to authenticated
using (public.is_content_admin())
with check (public.is_content_admin());

drop policy if exists "Public can read flat tours" on public.flat_tours;
create policy "Public can read flat tours"
on public.flat_tours for select
to anon, authenticated
using (true);

drop policy if exists "Admin manages flat tours" on public.flat_tours;
create policy "Admin manages flat tours"
on public.flat_tours for all
to authenticated
using (public.is_content_admin())
with check (public.is_content_admin());

insert into storage.buckets
  (id, name, public, file_size_limit, allowed_mime_types)
values
  (
    'content-media',
    'content-media',
    true,
    10485760,
    array['image/jpeg', 'image/png', 'image/webp', 'image/gif']
  ),
  (
    'flat-tours',
    'flat-tours',
    true,
    524288000,
    array['video/mp4', 'video/webm', 'video/quicktime']
  )
on conflict (id) do update set
  public = excluded.public,
  file_size_limit = excluded.file_size_limit,
  allowed_mime_types = excluded.allowed_mime_types;

drop policy if exists "Public reads OM content media" on storage.objects;
create policy "Public reads OM content media"
on storage.objects for select
to anon, authenticated
using (bucket_id in ('content-media', 'flat-tours'));

drop policy if exists "Admin uploads OM content media" on storage.objects;
create policy "Admin uploads OM content media"
on storage.objects for insert
to authenticated
with check (
  bucket_id in ('content-media', 'flat-tours')
  and public.is_content_admin()
);

drop policy if exists "Admin updates OM content media" on storage.objects;
create policy "Admin updates OM content media"
on storage.objects for update
to authenticated
using (
  bucket_id in ('content-media', 'flat-tours')
  and public.is_content_admin()
)
with check (
  bucket_id in ('content-media', 'flat-tours')
  and public.is_content_admin()
);

drop policy if exists "Admin deletes OM content media" on storage.objects;
create policy "Admin deletes OM content media"
on storage.objects for delete
to authenticated
using (
  bucket_id in ('content-media', 'flat-tours')
  and public.is_content_admin()
);

do $$
declare
  target_table text;
begin
  foreach target_table in array array[
    'blog_posts',
    'founder_profiles',
    'founder_projects',
    'customer_stories',
    'flat_tours'
  ]
  loop
    if not exists (
      select 1
      from pg_publication_tables
      where pubname = 'supabase_realtime'
        and schemaname = 'public'
        and tablename = target_table
    ) then
      execute format(
        'alter publication supabase_realtime add table public.%I',
        target_table
      );
    end if;
  end loop;
end;
$$;
